### PR TITLE
Create it_it.json

### PR DESCRIPTION
**Pull request by VladAndreiMorariu**
Hi,
I don't know if you accept translations, but anyway, I've done the one in Italian.
I hope it can be helpful to someone.

### CODE REVIEW

**Comment by SecretOnline** [comment]
Thank you for taking the time to translate this mod! Just to check, I did run them back through Google Translate and they all looked great, so I'd be glad to merge this in. 

You can ignore the failed build, it errored when trying to post the screenshot comment. I'll have to look into why that happened... [It was successful](https://i.imgur.com/ZCZf8cx.png), so there's nothing to worry about.

I'll follow up by adding your name to the contributors list in the mod to credit you for your work. I'll probably let this sit for a couple of days before releasing, in case you want to make any changes or someone comes along with another language (which is probably unlikely).

Thanks again, I really appreciate you doing this.

**Comment by SecretOnline** [comment]
Just popping back in to say that I've released [version 1.3.3 of the mod](https://modrinth.com/mod/accessible-step/version/v1.3.3), which includes your changes!

**Comment by VladAndreiMorariu** [comment]
Thank you for your work!

**Comment by SecretOnline** [comment]
Hi @VladAndreiMorariu and happy new year! I hope you've enjoyed the holiday season.

I took some time over the holidays to update the mod and have added one new option (and tooltip) to the settings screen. It allows you to have different settings on different servers or worlds, so you don't have to go into the game's options as often.

|Translation key|English (US)|Description|
|---|---|---|
|`options.accessiblestep.perworld`|Custom Config for World|Appears on a button with the value, e.g. "Custom Config for World: OFF". The rest of the button text (": OFF")  is done using the game's built-in `options.generic_value`, `options.off`, and `options.on` so you won't need to do that bit.|
|`options.accessiblestep.perworld.tooltip`|Use different options on this world or server. Worlds without this option set will use the main configuration.|Tooltip for the above option.|

I plan on releasing it towards the end of the week, after I've done some final tests and ported the changes back to previous versions of the game, but I'm not in any rush so if you don't have time immediately that's fine. Either create a new PR or reply with what they should be and I'll add them in.

If you aren't able to help for any reason that's fine. Just let me know if you don't want me to reach out again in case anything new gets added past this point.

**Comment by VladAndreiMorariu** [comment]
Hi, happy new year to you! I hope you also had a lovely holiday season.
Don’t worry, it’s perfectly fine to ask, and you did the right thing. Here’s the translation:

| Translation key  | English (US) | Italian |
| --- | --- | --- |
| `options.accessiblestep.perworld`  | Custom Config for World  | Configurazione Personalizzata per il Mondo |
| `options.accessiblestep.perworld.tooltip`  | Use different options on this world or server. Worlds without this option set will use the main configuration.  | Utilizza opzioni diverse per questo mondo o server. I mondi senza questa opzione attivata utilizzeranno la configurazione principale. |

Feel free to ask again; when I have time, I'll be happy to help you.

**Pull request merged**
